package botdetector

var rules = []string{
	" ylt",
	"13tabs",
	"192.comagent",
	"2ip.ru",
	"404enemy",
	"7siters",
	"80legs",
	"a6-indexer",
	"admantx",
	"ahc",
	"apis-google",
	"aspseek",
	"aws security scanner",
	"abonti",
	"aboundex",
	"accoona-ai-agent",
	"acunetix",
	"adauth/",
	"addthis",
	"adminlabs",
	"adstxtaggregator",
	"airmail",
	"alibaba.security.heimdall",
	"allsubmitter",
	"alligator",
	"anarchie",
	"androiddownloadmanager",
	"anemone",
	"anglesharp",
	"ant.com",
	"anturis agent",
	"anyevent-http/",
	"apache droid",
	"apache openoffice",
	"apache-httpasyncclient",
	"apache-httpclient",
	"apachebench",
	"apexoo",
	"aportworm/",
	"appbeat/",
	"appengine-google",
	"applesyndication",
	"aprc/",
	"arachmo",
	"arachnophilia",
	"arukereso",
	"ask jeeves",
	"askquickly",
	"asterias",
	"astute",
	"attach",
	"automaticwptester",
	"autonomy",
	"b-l-i-t-z-b-o-t",
	"bbbike",
	"bcklinks",
	"bdfetch",
	"bpimagewalker",
	"bubing",
	"backstreet",
	"backweb",
	"backlink-ceck",
	"backlinkhttpstatus",
	"bad-neighborhood",
	"badass",
	"bandit",
	"batchftp",
	"battleztar bazinga",
	"bazqux",
	"begunadvertising",
	"bewica-security-scan",
	"bidtellect",
	"bigbozz",
	"bigfoot",
	"binglocalsearch",
	"bingpreview",
	"bitacle",
	"black hole",
	"blackwidow",
	"blackboard safeassign",
	"blocknote.net",
	"blogbridge",
	"blogpulselive",
	"blogsearch",
	"bloglines",
	"bloglovin",
	"blogtrottr",
	"blowfish",
	"boost.beast",
	"braintree-webhooks",
	"branch metrics api",
	"branch-passthrough",
	"brandverity",
	"brandprotect",
	"brandwatch",
	"brodie/",
	"browsershots",
	"buck/",
	"buddy",
	"builtwith",
	"bullseye",
	"bunnyslippers",
	"burf search",
	"butterfly/",
	"buzzsumo",
	"caam/",
	"cc metadata scaper",
	"cert.at-statistics-survey",
	"cispa vulnerability notification",
	"cjnetworkquality",
	"cshttp",
	"csscheck",
	"cakephp",
	"calculon",
	"canary%20mail",
	"caretnail",
	"cegbfeieh",
	"cerberian drtrs",
	"changesmeter",
	"charlotte",
	"checkhost",
	"cherrypicker",
	"chinaclaw",
	"chirp/",
	"chlooe",
	"chromaxa",
	"cirrusexplorer",
	"citoid",
	"clarsentia",
	"cloud mapping",
	"cloudendure",
	"cloudflare-alwaysonline",
	"cloudflare-healthchecks",
	"cloudinary",
	"commafeed",
	"commons-httpclient",
	"cookiereports",
	"copyrightcheck",
	"copyscape",
	"cosmos4j.feedback",
	"covario-ids",
	"craw/",
	"crescent",
	"criteo",
	"crowsnest",
	"curious george",
	"dap/nethttp",
	"dmbrowser",
	"dnspod-reporting",
	"dts agent",
	"dareboost",
	"datacha0s",
	"dataxu",
	"databasedrivermysqli",
	"datafeedwatch",
	"datanyze",
	"dataparksearch",
	"daumoa",
	"daum",
	"demon",
	"deusu",
	"devil",
	"digg",
	"digincore",
	"digitalpebble",
	"dirbuster",
	"discourse forum onebox",
	"dispatch/",
	"disqus/",
	"dittospyder",
	"dolphin http client",
	"domainappender",
	"domainlabz",
	"donuts content explorer",
	"download wonder",
	"downtimedetector",
	"drip",
	"drupal (+http://drupal.org/)",
	"duplexweb-google",
	"earthcom",
	"eccp",
	"email exractor",
	"email wolf",
	"easy-thumb",
	"easydl",
	"ebingbong",
	"ecxi",
	"eirgrabber",
	"electricmonk",
	"emailwolf",
	"embarcadero",
	"embed php library",
	"embedly",
	"eventmachine httpclient",
	"everwall link expander",
	"evidon",
	"evrinid",
	"exactsearch",
	"exaleadcloudview",
	"excel/",
	"exorank",
	"exploratodo",
	"express webpictures",
	"extreme picture finder",
	"eyenetie",
	"fhscan",
	"faraday v",
	"favorg",
	"faveeo",
	"favicon downloader",
	"feed wrangler",
	"feedbooster",
	"feedbucket",
	"feedbunch/",
	"feedburner",
	"feedzcollector",
	"feedable/",
	"feedbin",
	"feedly",
	"feedshowonline",
	"feedspot",
	"feedwind/",
	"fetch api",
	"fetch/",
	"fever/",
	"filestack",
	"fimap",
	"flashget",
	"flipboardbrowserproxy",
	"flipboardproxy",
	"flipboardrss",
	"flunky",
	"foundseotool",
	"freeuploader",
	"funnelback",
	"fuzz faster u fool",
	"g-i-g-a-b-o-t",
	"gis-labs",
	"grequests",
	"gt::www",
	"gtmetrix",
	"genieo",
	"gentlesource",
	"getcode",
	"getlinkinfo",
	"getright",
	"geturlinfo/",
	"getweb",
	"getintent",
	"geziyor",
	"ghost inspector",
	"gigablastopensource",
	" package http",
	"go http package",
	"go!zilla",
	"go-ahead-got-it",
	"go-http-client",
	"gospotcheck",
	"gozilla",
	"goldfire server",
	"gomezagent",
	"goodzer/",
	"google appsviewer",
	"google desktop",
	"google keyword suggestion",
	"google keyword tool",
	"google pp default",
	"google page speed insights",
	"google search console",
	"google web preview",
	"google favicon",
	"google-ads-overview",
	"google-adwords",
	"google-apps-script",
	"google-calendar-importer",
	"google-http-java-client",
	"google-hoteladsverifier",
	"google-publisher-plugin",
	"google-read-aloud",
	"google-searchbyimage",
	"google-site-verification",
	"google-structured-data-testing-tool",
	"google-transparency-report",
	"google-youtube-links",
	"google-speakr",
	"googledocs",
	"googlehc/",
	"googleproducer",
	"googlesites",
	"gookey",
	"gotit",
	"grabnet",
	"grafula",
	"grammarly",
	"grapefx",
	"greatnews",
	"gregarius",
	"guzzlehttp",
	"rtland http client",
	"headmasterseo",
	"hmview",
	"htmlparser",
	"http banner detection",
	"http-header-abfrage",
	"http-tiny",
	"http::lite",
	"httpmon",
	"http_compression_test",
	"httpie",
	"haansoft",
	"hadi agent",
	"happyapps-webcheck",
	"hatena",
	"havij",
	"haxermen",
	"headlesschrome",
	"heartrails_capture",
	"hexometer",
	"hloader",
	"holmes",
	"honesosearchengine",
	"hootsuite image proxy",
	"hootsuite-webfeed",
	"hosttracker",
	"httpcomponents",
	"httpurlconnection",
	"hubspot ",
	"humanlinks",
	"idg twitter links resolver",
	"idwhois/",
	"iodc",
	"ioi",
	"ips/",
	"ipworks http/s component",
	"izabee",
	"iblog",
	"id-search",
	"ideelaborplagiaat",
	"iframely",
	"iltrovatore",
	"image fetch",
	"image sucker",
	"imageengine/",
	"imagevisu/",
	"imagga",
	"inagist",
	"indesign%20cc",
	"indy library",
	"ineturl",
	"infotekies",
	"infowizards reciprocal link",
	"instapaper",
	"integrity",
	"intelliseek",
	"interget",
	"internet ninja",
	"internetseer",
	"iria",
	"irokez",
	"jahho",
	"js-kit",
	"jaunt/",
	"jbrofuzz",
	"jersey/",
	"jetcar",
	"jigsaw",
	"jobfeed discovery",
	"jobboerse",
	"jobg8 url monitor",
	"jobrapido",
	"jobsearch1.5",
	"joinvision generic",
	"jolokiapwn",
	"joomla",
	"jorgee",
	"justview",
	"kocmohabt",
	"kaspersky lab cfr link resolver",
	"kelny/",
	"kerrigan/",
	"keycdn",
	"keyword density",
	"keywords research",
	"kickfire",
	"kimonolabs/",
	"kml-google",
	"kumkie",
	"lwp::simple",
	"lyt.sr",
	"l.webis",
	"larbin",
	"lavf/",
	"leechftp",
	"leechget",
	"lftp",
	"libvlc",
	"libweb",
	"libwhisker",
	"licorne",
	"liferea/",
	"lighthouse",
	"lightspeedsystems",
	"likse",
	"link valet",
	"linkalarm/",
	"linkexaminer",
	"linkpreviewgenerator",
	"linkscan",
	"linktiger",
	"linkwalker",
	"linksmanager",
	"lipperhey",
	"litemage_walker",
	"loadimpactrload",
	"longurl api",
	"mfc_tear_sample",
	"midown tool",
	"miixpc",
	"ms web services client protocol",
	"msfrontpage",
	"mvaclient",
	"mag-net",
	"magpierss",
	"mailchimp",
	"mail.ru",
	"majestic12",
	"mandrill",
	"mappercmd",
	"markmonitor",
	"markwatch",
	"mass downloader",
	"mata hari",
	"mediametric",
	"mediapartners-google",
	"megaindex.ru",
	"meltwaternews",
	"melvil rawi",
	"memgator",
	"metauri",
	"metaspinner",
	"micromessenger/",
	"microsearch",
	"microsoft data access",
	"microsoft office ",
	"microsoft outlook",
	"microsoft windows network diagnostics",
	"microsoft-webdav-miniredir",
	"mindjet",
	"miniature.io",
	"miniflux",
	"mister pix",
	"mixmax-linkpreview",
	"mnogosearch",
	"mojeek",
	"mojolicious (perl)",
	"montools",
	"monit/",
	"monitority/",
	"moreover",
	"morfeus fucking scanner",
	"morning paper",
	"movabletype",
	"mr.4x3 powered",
	"mrcgiguy",
	"muckrack/",
	"mxtoolbox/",
	"netcraft",
	"ng-search",
	"nicerspro",
	"nlnz_iaharvester",
	"nyu",
	"najdi.si",
	"name intelligence",
	"nameprotect",
	"navroad",
	"nearsite",
	"needle",
	"nessus",
	"net vampire",
	"netants",
	"netlyzer",
	"netmechanic",
	"netshelter contentscan",
	"netsystemsresearch",
	"nettrack",
	"netzip",
	"netpursual",
	"netsparker",
	"netvibes",
	"neustar wpm",
	"neutrinoapi",
	"newrelicpinger",
	"^newsblur ",
	"newsgator",
	"nexgate ruby client",
	"nibbler",
	"nikto",
	"nmap scripting engine",
	"nodeping",
	"nodemeter",
	"norton-safeweb",
	"notifixious",
	"notionembedder",
	"nuzzel",
	"nymesis",
	"omsc",
	"oppo a33",
	"ocelli/",
	"octopus",
	"offline explorer",
	"offline navigator",
	"ogscrper",
	"online domain tools",
	"opencalaissemanticproxy",
	"openlinkprofiler",
	"openvas",
	"openfind",
	"openstat/",
	"optimizer",
	"orbiter",
	"orgprobe/",
	"outlook-express",
	"outlook-ios",
	"owler",
	"oxfordcloudservice",
	"pecl::http",
	"poe-component-client-http",
	"prtg network monitor",
	"ptst ",
	"ptst/",
	"page valet",
	"pagefreezer",
	"pagegrabber",
	"pagepeeker",
	"pagescorer",
	"pagespeed/",
	"panopta",
	"papa foto",
	"pavuk",
	"paypal ipn",
	"pcore-http",
	"pearltrees",
	"peew",
	"peoplepal",
	"perlu -",
	"phantomjs screenshoter",
	"phantomjs/",
	"photon/",
	"pi-monster",
	"picscout",
	"picsearch",
	"picturefinder",
	"pimonster",
	"pingadmin.ru",
	"pingspot",
	"pingability",
	"pingdom",
	"pingoscope",
	"pixray",
	"pizilla",
	"plagger/",
	"ploetz + zeller",
	"plukkie",
	"pocketimagecache",
	"pocketparser",
	"pockey",
	"polymail/",
	"pompos",
	"porkbun",
	"port monitor",
	"postpost",
	"postmanruntime",
	"powerpoint/",
	"prebid",
	"priceonomics analysis engine",
	"printfriendly",
	"prittorrent",
	"prlog",
	"prowebwalker",
	"project 25499",
	"protopage",
	"pump",
	"python-httplib2",
	"python-urllib",
	"qqdownload",
	"qirina hurdler",
	"qrafterpro",
	"qseero",
	"qualidator",
	"queryn metasearch",
	"quora link preview",
	"qwantify",
	"roi hunter",
	"rpt-httpclient",
	"rssowl",
	"radian6",
	"rankactive",
	"rankflex",
	"ranksonicsiteauditor",
	"re-re studio",
	"reget",
	"reactornetty",
	"readability",
	"realdownload",
	"realplayer%20downloader",
	"rebelmouse",
	"recorder",
	"recurpost/",
	"reederformac",
	"reeder/",
	"repomonkey",
	"responsecodetest",
	"restsharp",
	"riddler",
	"rival iq",
	"robosourcer",
	"robozilla",
	"ryowlengine",
	"sbider",
	"seo browser",
	"seocentro",
	"seokicks",
	"seolizer",
	"seoprofiler",
	"seosearch",
	"seostats",
	"sistrix",
	"smrf url expander",
	"smurlexpander",
	"spdycheck",
	"speng",
	"ssl labs",
	"salesintelligent",
	"saleslift",
	"saucenao",
	"scamadviser-frontend",
	"scanalert",
	"scoop",
	"scoutjet",
	"scouturlmonitor",
	"scrapebox page scanner",
	"scrapy",
	"screaming",
	"screenshotservice",
	"scrubby",
	"scrutiny/",
	"search37",
	"searchexpress",
	"searchsight",
	"searchestate",
	"seeker",
	"semiocast http client",
	"semrush",
	"sendsay.ru",
	"seo servis",
	"seocheck",
	"seobility",
	"seomoz",
	"seznam",
	"shelob",
	"shodan",
	"shopwiki",
	"shoppimon",
	"shortlinktranslate",
	"sideqik",
	"simplepie",
	"simplyfast",
	"siphon",
	"site sucker",
	"site-shot/",
	"site24x7",
	"sitebar",
	"sitecondor",
	"siteexplorer",
	"siteguardian",
	"siteindexed",
	"sitemonitor",
	"sitesnagger",
	"sitesucker",
	"sitetruth",
	"sitebeam",
	"sitebulb/",
	"siteimprove",
	"sitemap generator",
	"sitemaps generator",
	"sitemapgenerator",
	"siteshooter b0t",
	"sitevigil",
	"skypeuripreview",
	"slack/",
	"slysearch",
	"smartdownload",
	"snake",
	"snapsearch",
	"snappy",
	"snarfer/",
	"sniffrss",
	"snoopy",
	"snowhaze search",
	"sortsite",
	"sottopop",
	"spacebison",
	"spamexperts",
	"spammen",
	"spanner",
	"specificfeeds",
	"spinn3r",
	"sprinklr ",
	"sqlworm",
	"sqworm",
	"stackrambler",
	"statastico/",
	"statuscake",
	"steeler",
	"stratagems kumo",
	"stroke.cz",
	"studiofaca",
	"stumbleupon",
	"sucuri",
	"superhttp",
	"surphace scout",
	"suzuran",
	"symfony browserkit",
	"symfony2 browserkit",
	"synhttpclient-built",
	"sysomos",
	"szukacz",
	"t0phackteam",
	"tlsprobe/",
	"tarantula/",
	"taringa ugc",
	"tarmotgezgin",
	"teleport",
	"telesoft",
	"telesphoreo",
	"telesphorep",
	"tenon.io",
	"test certificate info",
	"tetrahedron",
	"textrazor downloader",
	"the drop reaper",
	"the expert html source viewer",
	"the intraformant",
	"the knowledge ai",
	"thenomad",
	"thinklab",
	"thumbsniper",
	"thumbor",
	"thumbshots",
	"tineye",
	"tiny tiny rss",
	"toata",
	"traackr.com",
	"trackuity",
	"trapitagent",
	"trendiction",
	"trendsmap",
	"tryjsoup",
	"tulipchain",
	"turingos",
	"turnitin",
	"tweetminster",
	"tweezler/",
	"twice",
	"twikle",
	"twingly",
	"twisted pagegetter",
	"typhoeus",
	"url verifier",
	"urltester",
	"urlitor",
	"urly warning",
	"urly.warning",
	"udmsearch",
	"universalfeedparser",
	"unshorten.it",
	"untiny",
	"unwindfetchor",
	"upflow",
	"uptimia",
	"urltrends ranking updater",
	"urlcheckr",
	"urlstat",
	"vb project",
	"vci",
	"vsagent/",
	"vsb-tuo/",
	"vyu2",
	"vacuum",
	"vagabondo",
	"virusdie",
	"voideye",
	"voil",
	"vulnbusters meter",
	"w3c-checklink",
	"w3c-mobileok",
	"w3c_unicorn",
	"wac-ofu",
	"wdt.io",
	"wepa",
	"wp engine install performance api",
	"wpscan",
	"www-collector-e",
	"www-mechanize",
	"www::document",
	"www::mechanize",
	"wwwoffle",
	"wallpapershd",
	"wallpapers/",
	"wappalyzer",
	"watchmouse",
	"wbsrch/",
	"welikelinks",
	"wesee",
	"web auto",
	"web collage",
	"web enhancer",
	"web fetch",
	"web fuck",
	"web pix",
	"web sauger",
	"web sucker",
	"web spyder",
	"web-sniffer",
	"webauto",
	"webcapture",
	"webclient/",
	"webcookies",
	"webcopier",
	"webcorp",
	"webdatastats",
	"webdoc",
	"webenhancer",
	"webfetch",
	"webfuck",
	"webgazer",
	"webgo is",
	"webimagecollector",
	"webimages",
	"webindex",
	"webleacher",
	"webpix",
	"webreaper",
	"websauger",
	"websniffer",
	"webstripper",
	"websucker",
	"webthumbnail",
	"webwhacker",
	"webzip",
	"webalta",
	"webauskunft",
	"webshag",
	"webshot",
	"website quester",
	"websitequester",
	"websnapr",
	"webster",
	"webthumb/",
	"wfuzz/",
	"whatweb",
	"whatsapp",
	"whatsmyip",
	"wheregoes",
	"whibse",
	"whorunscoinhive",
	"whynder magnet",
	"^winhttp-autoproxy-service/",
	"winpodder",
	"windows-rss-platform",
	"woko",
	"wolfram httpclient",
	"wordpress/",
	"word/",
	"wordupinfosearch",
	"wtrace",
	"xing-contenttabreceiver",
	"xaxissemanticsclassifier",
	"xenu link sleuth",
	"^y!j-asr",
	"^y!j-bsc",
	"yp.pl",
	"y!j-brw",
	"yaanb",
	"yahoo link preview",
	"yahoocachesystem",
	"yahooysmcm",
	"yandeg",
	"yandex",
	"yo-yo",
	"yoys.net",
	"yoleo consumer",
	"yottaamonitor",
	"your-website-sucks",
	"zabbix",
	"zade",
	"zao",
	"zauba",
	"zemanta aggregator",
	"zend\\http\\client",
	"zend_http_client",
	"zermelo",
	"zeus ",
	"znhttp",
	"znajdzfoto",
	"zombie.js",
	"zoom.mac",
	"zyborg",
	"bot",
	"crawl",
	"archiver",
	"transcoder",
	"spider",
	"uptime",
	"validator",
	"fetcher",
	"cron",
	"checker",
	"reader",
	"extractor",
	"monitoring",
	"analyzer",
	"scraper",
	"^amazon simple notification service agent$",
	"^comodo dcv",
	"^calypso v/",
	"^dangdang",
	"^davclnt",
	"^fdm ",
	"^goose/",
	"^grabber",
	"^httpclient/",
	"^java/",
	"^jeode/",
	"^jetty/",
	"^mail/",
	"^mget",
	"^microsoft url control",
	"^ng/",
	"^ning/",
	"^php/",
	"^rma/",
	"^ruby",
	"^vse/",
	"^wordpress.com",
	"^xrl/",
	"^zmeu",
	"^b0t$",
	"^bluefish ",
	"^git/",
	"a3logics.in",
	"a.pr-cy.ru",
	"aboutthedomain",
	"acoon",
	"acrylicapps.com/pulp",
	"adbeat",
	"adressendeutschland",
	"adreview/",
	"adscanner",
	"adstxt-worker",
	"adstxt.com",
	"agentslug",
	"aihit",
	"aiohttp/",
	"akka-http/",
	"akula/",
	"alertra",
	"alexa site audit",
	"allloadin",
	"alyze.info",
	"amagit",
	"annotate_google",
	"arachnode",
	"aria2",
	"asafaweb",
	"asynchttp",
	"attohttpc",
	"autocite",
	"axios/",
	"backlink-check",
	"baidu.com",
	"basicstate",
	"baypup/",
	"binu image cacher",
	"biglotron",
	"binlar",
	"biz_directory",
	"boitho.com-dc",
	"catexplorador",
	"censys",
	"cg-eye",
	"changedetection",
	"checkprivacy",
	"chkme.com",
	"clips.ua.ac.be",
	"cmcm.com",
	"coccoc",
	"cognitiveseo",
	"colly -",
	"commonscan",
	"contactbigdatafr",
	"contentkingapp",
	"convera",
	"copyright sheriff",
	"cortex/",
	"curb",
	"curl",
	"cuwhois/",
	"cybo.com",
	"dbpoweramp",
	"dataprovider",
	"ddline",
	"deeris",
	"delve.ai",
	"developers.google.com/+/web/snippet/",
	"dlvr",
	"docoloc",
	"dotmailer content retrieval",
	"dotsemantic",
	"downforeveryoneorjustme",
	"downnotifier",
	"drupact",
	"dubaiindex",
	"ecairn-grabber",
	"ecatch",
	"econtext/",
	"ec2linkfinder",
	"elefent",
	"endo/",
	"europarchive.org",
	"evc-batch",
	"exif",
	"ezooms",
	"facebookexternalhit",
	"facebookexternalua",
	"facebookplatform",
	"fairshare",
	"fasthttp",
	"faviconarchive",
	"faviconkit",
	"feeder",
	"feeltiptop",
	"findlink",
	"findthatfile",
	"fluffy",
	"flynxapp",
	"forensiq",
	"free thumbnails",
	"g00g1e.net",
	"gsoap/",
	"ganarvisitas",
	"geek-tools",
	"getprismatic",
	"getroot",
	"github-camo",
	"github.com",
	"gobyus",
	"gofetch",
	"gooblog",
	"google-xrawler",
	"gosquared-thumbnailer",
	"grabify",
	"grokkit",
	"grouphigh",
	"grub-client",
	"gvfs/",
	"hackney/",
	"help@dataminr.com",
	"heritrix",
	"historious",
	"hkedcity",
	"hledejlevne.cz",
	"hosterstats",
	"ht://check",
	"htdig",
	"htmlyse",
	"http-get",
	"http-kit",
	"http-request/",
	"http://www.neomo.de/",
	"httprequest",
	"http.rb/",
	"http_get",
	"http_request2",
	"http_requester",
	"httphr",
	"httpscheck",
	"httpssites_power",
	"httpunit",
	"httrack",
	"huaweisymantec",
	"i2kconnect/",
	"ithemes sync/",
	"izsearch",
	"ichiro",
	"igdespyder",
	"imagineeasy",
	"imgsizer",
	"inbound.li parser",
	"infegy",
	"infohelfer",
	"inpwrd.com",
	"instabid",
	"integromedb",
	"internetvista monitor",
	"internet_archive",
	"internetwache",
	"intravnews",
	"iplabel",
	"ips-agent",
	"iqdb/",
	"isup.li",
	"isitup.org",
	"iskanie",
	"janforman",
	"jobo",
	"khttp/",
	"knows.is",
	"kouio",
	"kube-probe",
	"kubectl",
	"kulturarw3",
	"letsencrypt",
	"libwww",
	"limber.io",
	"linkcheck",
	"link_thumbnailer",
	"linkdex",
	"linkfluence",
	"linkpeek",
	"livedoor screenshot",
	"localsearch-web",
	"longurl-r-package",
	"looid.com",
	"looksystems.net",
	"ltx71",
	"lua-resty-http",
	"lwp-request",
	"lwp-trivial",
	"lycos",
	"mshots",
	"mabontland",
	"makecontact/",
	"marketinggrader",
	"masscan/",
	"mediawords",
	"mixdata dot com",
	"mixed-content-scan",
	"mixnode",
	"mogimogi",
	"monitis",
	"montastic",
	"mowser",
	"muhstik-scan",
	"nwormfeedfinder",
	"nagios",
	"netresearch",
	"newsme",
	"newspaper/",
	"nineconnections",
	"node-superagent",
	"node-urllib",
	"node.io",
	"nominet.org.uk",
	"nominet.uk",
	"notifyninja",
	"nuhk",
	"nutch",
	"nyawc/",
	"oegp",
	"okhttp",
	"omgili",
	"orion-semantics",
	"ow.ly",
	"owncloud news",
	"page scorer",
	"page2rss",
	"page_verifier",
	"panscient",
	"parsijoo",
	"pcbrowser",
	"peerindex",
	"phpservermon",
	"ping.blo.gs",
	"pinterest.com",
	"plumanalytics",
	"postano",
	"postrank",
	"probethenet",
	"prospectb2b",
	"proximic",
	"pshtt, https scanning",
	"python-httpx",
	"python-requests",
	"queuedriver",
	"redback/",
	"request.js",
	"reqwest/",
	"safe-agent-scanner",
	"sc-downloader",
	"scalaj-http",
	"scan.lol",
	"scooter",
	"search.thunderstone",
	"searchenginepromotionhelp",
	"semanticdiscovery",
	"semanticjuice",
	"sentry/",
	"seo-nastroj.cz",
	"seo4ajax",
	"seoscanners",
	"seositecheckup",
	"servernfo",
	"sexsearcher",
	"shorturl lengthener",
	"shrinktheweb",
	"sitexy.com",
	"slider.com",
	"slurp",
	"sniptracker",
	"sogou web",
	"sovereign.ai",
	"spaziodati",
	"speedy",
	"spray-can",
	"spyonweb",
	"sqlmap",
	"ssl-tools",
	"suchen",
	"summify",
	"sysscan",
	"takeout",
	"teoma",
	"terrainformatica",
	"testuri",
	"theinternetrules",
	"timewe.net",
	"topster",
	"touche.com",
	"tracemyfile",
	"trendspottr",
	"truwogps",
	"tweetedtimes",
	"twibble",
	"ubermetrics-technologies",
	"uclassify",
	"unchaos",
	"unirest-java",
	"updated",
	"updown.io daemon",
	"urlresolver",
	"vbseo",
	"via ggpht.com googleimageproxy",
	"visionutils",
	"vkshare",
	"voltron",
	"voyager/",
	"w3af.org",
	"wangling",
	"web-capture.net",
	"webcollage",
	"webkit2png",
	"webmastercoffee",
	"webmon ",
	"webscreenie",
	"websitepulse agent",
	"wf84",
	"wget",
	"wkhtmlto",
	"wmtips",
	"woorankreview",
	"worldping-api",
	"wotbox",
	"wpif",
	"wprecon.com survey",
	"wscheck",
	"www.monitor.us",
	"x09mozilla",
	"x22mozilla",
	"xpymep",
	"yacy",
	"yanga",
	"yeti",
	"yooglifetchagent",
	"yourls.org",
	"zgrab",
	// Manual rules
	"^!susie",
	"^binget/",
	"^blackfire php player/",
	"^cocoal.icio.us/",
	"^cynthia ",
	"^java1.",
	"^Mozilla/5.0 (compatible; https://disqus.com)$",
	"^nitro pdf download$",
	"^peach/",
	"^web downloader/",
}
