package botdetector

var rules = []string{
	" package http",
	" ylt ",
	"//disqus.com",
	"13tabs",
	"192.comagent",
	"2ip.ru",
	"404enemy",
	"7siters",
	"80legs",
	"^!susie",
	"^amazon simple notification service agent$",
	"^b0t$",
	"^binget/",
	"^blackfire php player/",
	"^bluefish ",
	"^calypso v/",
	"^cocoal.icio.us/",
	"^comodo dcv",
	"^cynthia ",
	"^dangdang",
	"^davclnt",
	"^fdm ",
	"^git/",
	"^goose/",
	"^grabber",
	"^httpclient/",
	"^java/",
	"^java1.",
	"^jeode/",
	"^jetty/",
	"^mail/",
	"^mget",
	"^microsoft url control",
	"^newsblur ",
	"^ng/",
	"^ning/",
	"^nitro pdf download$",
	"^peach/",
	"^php/",
	"^rma/",
	"^ruby",
	"^vse/",
	"^web downloader/",
	"^winhttp-autoproxy-service/",
	"^wordpress.com",
	"^xrl/",
	"^y!j-asr",
	"^y!j-bsc",
	"^zmeu",
	"a.pr-cy.ru",
	"a3logics.in",
	"a6-indexer",
	"abonti",
	"aboundex",
	"aboutthedomain",
	"accoona-ai-agent",
	"acoon",
	"acrylicapps.com/pulp",
	"acunetix",
	"adauth/",
	"adbeat",
	"addthis",
	"admantx",
	"adminlabs",
	"adressendeutschland",
	"adreview/",
	"adscanner",
	"adstxt-worker",
	"adstxt.com",
	"adstxtaggregator",
	"agentslug",
	"ahc",
	"aihit",
	"aiohttp/",
	"airmail",
	"akka-http/",
	"akula/",
	"alertra",
	"alexa site audit",
	"alibaba.security.heimdall",
	"alligator",
	"allloadin",
	"allsubmitter",
	"alyze.info",
	"amagit",
	"analyzer",
	"anarchie",
	"androiddownloadmanager",
	"anemone",
	"anglesharp",
	"annotate_google",
	"ant.com",
	"anturis agent",
	"anyevent-http/",
	"apache droid",
	"apache openoffice",
	"apache-httpasyncclient",
	"apache-httpclient",
	"apachebench",
	"apexoo",
	"apis-google",
	"aportworm/",
	"appbeat/",
	"appengine-google",
	"applesyndication",
	"aprc/",
	"arachmo",
	"arachnode",
	"arachnophilia",
	"archiver",
	"aria2",
	"arukereso",
	"asafaweb",
	"ask jeeves",
	"askquickly",
	"aspseek",
	"asterias",
	"astute",
	"asynchttp",
	"attach",
	"attohttpc",
	"autocite",
	"automaticwptester",
	"autonomy",
	"aws security scanner",
	"axios/",
	"b-l-i-t-z-b-o-t",
	"backlink-ceck",
	"backlink-check",
	"backlinkhttpstatus",
	"backstreet",
	"backweb",
	"bad-neighborhood",
	"badass",
	"baidu.com",
	"bandit",
	"basicstate",
	"batchftp",
	"battleztar bazinga",
	"baypup/",
	"bazqux",
	"bbbike",
	"bcklinks",
	"bdfetch",
	"begunadvertising",
	"bewica-security-scan",
	"bidtellect",
	"bigbozz",
	"bigfoot",
	"biglotron",
	"binglocalsearch",
	"bingpreview",
	"binlar",
	"binu image cacher",
	"bitacle",
	"biz_directory",
	"black hole",
	"blackboard safeassign",
	"blackwidow",
	"blocknote.net",
	"blogbridge",
	"bloglines",
	"bloglovin",
	"blogpulselive",
	"blogsearch",
	"blogtrottr",
	"blowfish",
	"boitho.com-dc",
	"boost.beast",
	"bot",
	"bpimagewalker",
	"braintree-webhooks",
	"branch metrics api",
	"branch-passthrough",
	"brandprotect",
	"brandverity",
	"brandwatch",
	"brodie/",
	"browsershots",
	"bubing",
	"buck/",
	"buddy",
	"builtwith",
	"bullseye",
	"bunnyslippers",
	"burf search",
	"butterfly/",
	"buzzsumo",
	"caam/",
	"cakephp",
	"calculon",
	"canary%20mail",
	"caretnail",
	"catexplorador",
	"cc metadata scaper",
	"cegbfeieh",
	"censys",
	"cerberian drtrs",
	"cert.at-statistics-survey",
	"cg-eye",
	"changedetection",
	"changesmeter",
	"charlotte",
	"checker",
	"checkhost",
	"checkprivacy",
	"cherrypicker",
	"chinaclaw",
	"chirp/",
	"chkme.com",
	"chlooe",
	"chromaxa",
	"cirrusexplorer",
	"cispa vulnerability notification",
	"citoid",
	"cjnetworkquality",
	"clarsentia",
	"clips.ua.ac.be",
	"cloud mapping",
	"cloudendure",
	"cloudflare-alwaysonline",
	"cloudflare-healthchecks",
	"cloudinary",
	"cmcm.com",
	"coccoc",
	"cognitiveseo",
	"colly -",
	"commafeed",
	"commons-httpclient",
	"commonscan",
	"contactbigdatafr",
	"contentkingapp",
	"convera",
	"cookiereports",
	"copyright sheriff",
	"copyrightcheck",
	"copyscape",
	"cortex/",
	"cosmos4j.feedback",
	"covario-ids",
	"craw/",
	"crawl",
	"crescent",
	"criteo",
	"cron",
	"crowsnest",
	"cshttp",
	"csscheck",
	"curb",
	"curious george",
	"curl",
	"cuwhois/",
	"cybo.com",
	"dap/nethttp",
	"dareboost",
	"databasedrivermysqli",
	"datacha0s",
	"datafeedwatch",
	"datanyze",
	"dataparksearch",
	"dataprovider",
	"dataxu",
	"daum",
	"daumoa",
	"dbpoweramp",
	"ddline",
	"deeris",
	"delve.ai",
	"demon",
	"deusu",
	"developers.google.com/+/web/snippet/",
	"devil",
	"digg",
	"digincore",
	"digitalpebble",
	"dirbuster",
	"discourse forum onebox",
	"dispatch/",
	"disqus/",
	"dittospyder",
	"dlvr",
	"dmbrowser",
	"dnspod-reporting",
	"docoloc",
	"dolphin http client",
	"domainappender",
	"domainlabz",
	"domainsproject.org)$",
	"donuts content explorer",
	"dotmailer content retrieval",
	"dotsemantic",
	"downforeveryoneorjustme",
	"download wonder",
	"downnotifier",
	"downtimedetector",
	"drip",
	"drupact",
	"drupal (+http://drupal.org/)",
	"dts agent",
	"dubaiindex",
	"duplexweb-google",
	"dynatracesynthetic",
	"earthcom",
	"easy-thumb",
	"easydl",
	"ebingbong",
	"ec2linkfinder",
	"ecairn-grabber",
	"ecatch",
	"eccp",
	"econtext/",
	"ecxi",
	"eirgrabber",
	"electricmonk",
	"elefent",
	"email exractor",
	"email wolf",
	"emailwolf",
	"embarcadero",
	"embed php library",
	"embedly",
	"endo/",
	"europarchive.org",
	"evc-batch",
	"eventmachine httpclient",
	"everwall link expander",
	"evidon",
	"evrinid",
	"exactsearch",
	"exaleadcloudview",
	"excel/",
	"exif",
	"exorank",
	"exploratodo",
	"express webpictures",
	"extractor",
	"extreme picture finder",
	"eyenetie",
	"ezooms",
	"facebookexternalhit",
	"facebookexternalua",
	"facebookplatform",
	"fairshare",
	"faraday v",
	"fasthttp",
	"faveeo",
	"favicon downloader",
	"faviconarchive",
	"faviconkit",
	"favorg",
	"feed wrangler",
	"feedable/",
	"feedbin",
	"feedbooster",
	"feedbucket",
	"feedbunch/",
	"feedburner",
	"feeder",
	"feedly",
	"feedshowonline",
	"feedspot",
	"feedwind/",
	"feedzcollector",
	"feeltiptop",
	"fetch api",
	"fetch/",
	"fetcher",
	"fever/",
	"fhscan",
	"filestack",
	"fimap",
	"findlink",
	"findthatfile",
	"flashget",
	"flipboardbrowserproxy",
	"flipboardproxy",
	"flipboardrss",
	"fluffy",
	"flunky",
	"flynxapp",
	"forensiq",
	"foundseotool",
	"free thumbnails",
	"freeuploader",
	"funnelback",
	"fuzz faster u fool",
	"g-i-g-a-b-o-t",
	"g00g1e.net",
	"ganarvisitas",
	"geek-tools",
	"genieo",
	"gentlesource",
	"getcode",
	"getintent",
	"getlinkinfo",
	"getprismatic",
	"getright",
	"getroot",
	"geturlinfo/",
	"getweb",
	"geziyor",
	"ghost inspector",
	"gigablastopensource",
	"gis-labs",
	"github-camo",
	"github.com",
	"go http package",
	"go!zilla",
	"go-ahead-got-it",
	"go-http-client",
	"gobyus",
	"gofetch",
	"goldfire server",
	"gomezagent",
	"gooblog",
	"goodzer/",
	"google appsviewer",
	"google desktop",
	"google favicon",
	"google keyword suggestion",
	"google keyword tool",
	"google page speed insights",
	"google pp default",
	"google search console",
	"google web preview",
	"google-ads-overview",
	"google-adwords",
	"google-apps-script",
	"google-calendar-importer",
	"google-hoteladsverifier",
	"google-http-java-client",
	"google-publisher-plugin",
	"google-read-aloud",
	"google-searchbyimage",
	"google-site-verification",
	"google-speakr",
	"google-structured-data-testing-tool",
	"google-transparency-report",
	"google-xrawler",
	"google-youtube-links",
	"googledocs",
	"googlehc/",
	"googleproducer",
	"googlesites",
	"gookey",
	"gospotcheck",
	"gosquared-thumbnailer",
	"gotit",
	"gozilla",
	"grabify",
	"grabnet",
	"grafula",
	"grammarly",
	"grapefx",
	"greatnews",
	"gregarius",
	"grequests",
	"grokkit",
	"grouphigh",
	"grub-client",
	"gsoap/",
	"gt::www",
	"gtmetrix",
	"guzzlehttp",
	"gvfs/",
	"haansoft",
	"hackney/",
	"hadi agent",
	"happyapps-webcheck",
	"hatena",
	"havij",
	"haxermen",
	"headlesschrome",
	"headmasterseo",
	"heartrails_capture",
	"help@dataminr.com",
	"heritrix",
	"hexometer",
	"historious",
	"hkedcity",
	"hledejlevne.cz",
	"hloader",
	"hmview",
	"holmes",
	"honesosearchengine",
	"hootsuite image proxy",
	"hootsuite-webfeed",
	"hosterstats",
	"hosttracker",
	"ht://check",
	"htdig",
	"htmlparser",
	"htmlyse",
	"http banner detection",
	"http-get",
	"http-header-abfrage",
	"http-kit",
	"http-request/",
	"http-tiny",
	"http.rb/",
	"http://www.neomo.de/",
	"http::lite",
	"http_compression_test",
	"http_get",
	"http_request2",
	"http_requester",
	"httpcomponents",
	"httphr",
	"httpie",
	"httpmon",
	"httprequest",
	"httpscheck",
	"httpssites_power",
	"httpunit",
	"httpurlconnection",
	"httrack",
	"huaweisymantec",
	"hubspot ",
	"humanlinks",
	"i2kconnect/",
	"iblog",
	"ichiro",
	"id-search",
	"ideelaborplagiaat",
	"idg twitter links resolver",
	"idwhois/",
	"iframely",
	"igdespyder",
	"iltrovatore",
	"image fetch",
	"image sucker",
	"imageengine/",
	"imagevisu/",
	"imagga",
	"imagineeasy",
	"imgsizer",
	"inagist",
	"inbound.li parser",
	"indesign%20cc",
	"indy library",
	"ineturl",
	"infegy",
	"infohelfer",
	"infotekies",
	"infowizards reciprocal link",
	"inpwrd.com",
	"instabid",
	"instapaper",
	"integrity",
	"integromedb",
	"intelliseek",
	"interget",
	"internet ninja",
	"internet_archive",
	"internetseer",
	"internetvista monitor",
	"internetwache",
	"intravnews",
	"iodc",
	"ioi",
	"iplabel",
	"ips-agent",
	"ips/",
	"ipworks http/s component",
	"iqdb/",
	"iria",
	"irokez",
	"isitup.org",
	"iskanie",
	"isup.li",
	"ithemes sync/",
	"izabee",
	"izsearch",
	"jahho",
	"janforman",
	"jaunt/",
	"jbrofuzz",
	"jersey/",
	"jetcar",
	"jigsaw",
	"jobboerse",
	"jobfeed discovery",
	"jobg8 url monitor",
	"jobo",
	"jobrapido",
	"jobsearch1.5",
	"joinvision generic",
	"jolokiapwn",
	"joomla",
	"jorgee",
	"js-kit",
	"justview",
	"kaspersky lab cfr link resolver",
	"kelny/",
	"kerrigan/",
	"keycdn",
	"keyword density",
	"keywords research",
	"khttp/",
	"kickfire",
	"kimonolabs/",
	"kml-google",
	"knows.is",
	"kocmohabt",
	"kouio",
	"kube-probe",
	"kubectl",
	"kulturarw3",
	"kumkie",
	"l.webis",
	"larbin",
	"lavf/",
	"leechftp",
	"leechget",
	"letsencrypt",
	"lftp",
	"libvlc",
	"libweb",
	"libwhisker",
	"libwww",
	"licorne",
	"liferea/",
	"lighthouse",
	"lightspeedsystems",
	"likse",
	"limber.io",
	"link valet",
	"link_thumbnailer",
	"linkalarm/",
	"linkcheck",
	"linkdex",
	"linkexaminer",
	"linkfluence",
	"linkpeek",
	"linkpreviewgenerator",
	"linkscan",
	"linksmanager",
	"linktiger",
	"linkwalker",
	"lipperhey",
	"litemage_walker",
	"livedoor screenshot",
	"loadimpactrload",
	"localsearch-web",
	"longurl api",
	"longurl-r-package",
	"looid.com",
	"looksystems.net",
	"ltx71",
	"lua-resty-http",
	"lwp-request",
	"lwp-trivial",
	"lwp::simple",
	"lycos",
	"lyt.sr",
	"mabontland",
	"mag-net",
	"magpierss",
	"mail.ru",
	"mailchimp",
	"majestic12",
	"makecontact/",
	"mandrill",
	"mappercmd",
	"marketinggrader",
	"markmonitor",
	"markwatch",
	"mass downloader",
	"masscan/",
	"mata hari",
	"mediametric",
	"mediapartners-google",
	"mediawords",
	"megaindex.ru",
	"meltwaternews",
	"melvil rawi",
	"memgator",
	"metaspinner",
	"metauri",
	"mfc_tear_sample",
	"micromessenger/",
	"microsearch",
	"microsoft data access",
	"microsoft office ",
	"microsoft outlook",
	"microsoft windows network diagnostics",
	"microsoft-webdav-miniredir",
	"midown tool",
	"miixpc",
	"mindjet",
	"miniature.io",
	"miniflux",
	"mister pix",
	"mixdata dot com",
	"mixed-content-scan",
	"mixmax-linkpreview",
	"mixnode",
	"mnogosearch",
	"mogimogi",
	"mojeek",
	"mojolicious (perl)",
	"monit/",
	"monitis",
	"monitoring",
	"monitority/",
	"montastic",
	"montools",
	"moreover",
	"morfeus fucking scanner",
	"morning paper",
	"movabletype",
	"mowser",
	"mr.4x3 powered",
	"mrcgiguy",
	"ms web services client protocol",
	"msfrontpage",
	"mshots",
	"muckrack/",
	"muhstik-scan",
	"mvaclient",
	"mxtoolbox/",
	"nagios",
	"najdi.si",
	"name intelligence",
	"nameprotect",
	"navroad",
	"nearsite",
	"needle",
	"nessus",
	"net vampire",
	"netants",
	"netcraft",
	"netlyzer",
	"netmechanic",
	"netpursual",
	"netresearch",
	"netshelter contentscan",
	"netsparker",
	"netsystemsresearch",
	"nettrack",
	"netvibes",
	"netzip",
	"neustar wpm",
	"neutrinoapi",
	"newrelicpinger",
	"newsgator",
	"newsme",
	"newspaper/",
	"nexgate ruby client",
	"ng-search",
	"nibbler",
	"nicerspro",
	"nikto",
	"nineconnections",
	"nlnz_iaharvester",
	"nmap scripting engine",
	"node-superagent",
	"node-urllib",
	"node.io",
	"nodemeter",
	"nodeping",
	"nominet.org.uk",
	"nominet.uk",
	"norton-safeweb",
	"notifixious",
	"notifyninja",
	"notionembedder",
	"nuhk",
	"nutch",
	"nuzzel",
	"nwormfeedfinder",
	"nyawc/",
	"nymesis",
	"nyu",
	"ocelli/",
	"octopus",
	"oegp",
	"offline explorer",
	"offline navigator",
	"ogscrper",
	"okhttp",
	"omgili",
	"omsc",
	"online domain tools",
	"opencalaissemanticproxy",
	"openfind",
	"openlinkprofiler",
	"openstat/",
	"openvas",
	"oppo a33",
	"optimizer",
	"orbiter",
	"orgprobe/",
	"orion-semantics",
	"outlook-express",
	"outlook-ios",
	"ow.ly",
	"owler",
	"owncloud news",
	"oxfordcloudservice",
	"page scorer",
	"page valet",
	"page2rss",
	"page_verifier",
	"pagefreezer",
	"pagegrabber",
	"pagepeeker",
	"pagescorer",
	"pagespeed/",
	"panopta",
	"panscient",
	"papa foto",
	"parsijoo",
	"pavuk",
	"paypal ipn",
	"pcbrowser",
	"pcore-http",
	"pearltrees",
	"pecl::http",
	"peerindex",
	"peew",
	"peoplepal",
	"perlu -",
	"phantomjs screenshoter",
	"phantomjs/",
	"photon/",
	"phpservermon",
	"pi-monster",
	"picscout",
	"picsearch",
	"picturefinder",
	"pimonster",
	"ping.blo.gs",
	"pingability",
	"pingadmin.ru",
	"pingdom",
	"pingoscope",
	"pingspot",
	"pinterest.com",
	"pixray",
	"pizilla",
	"plagger/",
	"ploetz + zeller",
	"plukkie",
	"plumanalytics",
	"pocketimagecache",
	"pocketparser",
	"pockey",
	"poe-component-client-http",
	"polymail/",
	"pompos",
	"porkbun",
	"port monitor",
	"postano",
	"postmanruntime",
	"postpost",
	"postrank",
	"powerpoint/",
	"prebid",
	"priceonomics analysis engine",
	"printfriendly",
	"prittorrent",
	"prlog",
	"probethenet",
	"project 25499",
	"prospectb2b",
	"protopage",
	"prowebwalker",
	"proximic",
	"prtg network monitor",
	"pshtt, https scanning",
	"ptst ",
	"ptst/",
	"pump",
	"python-httplib2",
	"python-httpx",
	"python-requests",
	"python-urllib",
	"qirina hurdler",
	"qqdownload",
	"qrafterpro",
	"qseero",
	"qualidator",
	"queryn metasearch",
	"queuedriver",
	"quora link preview",
	"qwantify",
	"radian6",
	"rankactive",
	"rankflex",
	"ranksonicsiteauditor",
	"re-re studio",
	"reactornetty",
	"readability",
	"reader",
	"realdownload",
	"realplayer%20downloader",
	"rebelmouse",
	"recorder",
	"recurpost/",
	"redback/",
	"reeder/",
	"reederformac",
	"reget",
	"repomonkey",
	"request.js",
	"reqwest/",
	"responsecodetest",
	"restsharp",
	"riddler",
	"rival iq",
	"robosourcer",
	"robozilla",
	"roi hunter",
	"rpt-httpclient",
	"rssowl",
	"rtland http client",
	"ruxitsynthetic/",
	"ryowlengine",
	"safe-agent-scanner",
	"salesintelligent",
	"saleslift",
	"saucenao",
	"sbider",
	"sc-downloader",
	"scalaj-http",
	"scamadviser-frontend",
	"scan.lol",
	"scanalert",
	"scoop",
	"scooter",
	"scoutjet",
	"scouturlmonitor",
	"scrapebox page scanner",
	"scraper",
	"scrapy",
	"screaming",
	"screenshotservice",
	"scrubby",
	"scrutiny/",
	"search.thunderstone",
	"search37",
	"searchenginepromotionhelp",
	"searchestate",
	"searchexpress",
	"searchsight",
	"seeker",
	"semanticdiscovery",
	"semanticjuice",
	"semiocast http client",
	"semrush",
	"sendsay.ru",
	"sentry/",
	"seo browser",
	"seo servis",
	"seo-nastroj.cz",
	"seo4ajax",
	"seobility",
	"seocentro",
	"seocheck",
	"seokicks",
	"seolizer",
	"seomoz",
	"seoprofiler",
	"seoscanners",
	"seosearch",
	"seositecheckup",
	"seostats",
	"servernfo",
	"sexsearcher",
	"seznam",
	"shelob",
	"shodan",
	"shoppimon",
	"shopwiki",
	"shortlinktranslate",
	"shorturl lengthener",
	"shrinktheweb",
	"sideqik",
	"simplepie",
	"simplyfast",
	"siphon",
	"sistrix",
	"site sucker",
	"site-shot/",
	"site24x7",
	"sitebar",
	"sitebeam",
	"sitebulb/",
	"sitecondor",
	"siteexplorer",
	"siteguardian",
	"siteimprove",
	"siteindexed",
	"sitemap generator",
	"sitemapgenerator",
	"sitemaps generator",
	"sitemonitor",
	"siteshooter b0t",
	"sitesnagger",
	"sitesucker",
	"sitetruth",
	"sitevigil",
	"sitexy.com",
	"skypeuripreview",
	"slack/",
	"slider.com",
	"slurp",
	"slysearch",
	"smartdownload",
	"smrf url expander",
	"smurlexpander",
	"snake",
	"snappy",
	"snapsearch",
	"snarfer/",
	"sniffrss",
	"sniptracker",
	"snoopy",
	"snowhaze search",
	"sogou web",
	"sortsite",
	"sottopop",
	"sovereign.ai",
	"spacebison",
	"spamexperts",
	"spammen",
	"spanner",
	"spaziodati",
	"spdycheck",
	"specificfeeds",
	"speedy",
	"speng",
	"spider",
	"spinn3r",
	"spray-can",
	"sprinklr ",
	"spyonweb",
	"sqlmap",
	"sqlworm",
	"sqworm",
	"ssl labs",
	"ssl-tools",
	"stackrambler",
	"statastico/",
	"statuscake",
	"steeler",
	"stratagems kumo",
	"stroke.cz",
	"studiofaca",
	"stumbleupon",
	"suchen",
	"sucuri",
	"summify",
	"superhttp",
	"surphace scout",
	"suzuran",
	"symfony browserkit",
	"symfony2 browserkit",
	"synhttpclient-built",
	"sysomos",
	"sysscan",
	"szukacz",
	"t0phackteam",
	"takeout",
	"tarantula/",
	"taringa ugc",
	"tarmotgezgin",
	"teleport",
	"telesoft",
	"telesphoreo",
	"telesphorep",
	"tenon.io",
	"teoma",
	"terrainformatica",
	"test certificate info",
	"testuri",
	"tetrahedron",
	"textrazor downloader",
	"the drop reaper",
	"the expert html source viewer",
	"the intraformant",
	"the knowledge ai",
	"theinternetrules",
	"thenomad",
	"thinklab",
	"thumbor",
	"thumbshots",
	"thumbsniper",
	"timewe.net",
	"tineye",
	"tiny tiny rss",
	"tlsprobe/",
	"toata",
	"topster",
	"touche.com",
	"traackr.com",
	"tracemyfile",
	"trackuity",
	"transcoder",
	"trapitagent",
	"trendiction",
	"trendsmap",
	"trendspottr",
	"truwogps",
	"tryjsoup",
	"tulipchain",
	"turingos",
	"turnitin",
	"tweetedtimes",
	"tweetminster",
	"tweezler/",
	"twibble",
	"twice",
	"twikle",
	"twingly",
	"twisted pagegetter",
	"typhoeus",
	"ubermetrics-technologies",
	"uclassify",
	"udmsearch",
	"unchaos",
	"unirest-java",
	"universalfeedparser",
	"unshorten.it",
	"untiny",
	"unwindfetchor",
	"updated",
	"updown.io daemon",
	"upflow",
	"uptime",
	"uptimia",
	"url verifier",
	"urlcheckr",
	"urlitor",
	"urlresolver",
	"urlstat",
	"urltester",
	"urltrends ranking updater",
	"urly warning",
	"urly.warning",
	"vacuum",
	"vagabondo",
	"validator",
	"vb project",
	"vbseo",
	"vci",
	"via ggpht.com googleimageproxy",
	"virusdie",
	"visionutils",
	"vkshare",
	"voideye",
	"voil",
	"voltron",
	"voyager/",
	"vsagent/",
	"vsb-tuo/",
	"vulnbusters meter",
	"vyu2",
	"w3af.org",
	"w3c-checklink",
	"w3c-mobileok",
	"w3c_unicorn",
	"wac-ofu",
	"wallpapers/",
	"wallpapershd",
	"wangling",
	"wappalyzer",
	"watchmouse",
	"wbsrch/",
	"wdt.io",
	"web auto",
	"web collage",
	"web enhancer",
	"web fetch",
	"web fuck",
	"web pix",
	"web sauger",
	"web spyder",
	"web sucker",
	"web-capture.net",
	"web-sniffer",
	"webalta",
	"webauskunft",
	"webauto",
	"webcapture",
	"webclient/",
	"webcollage",
	"webcookies",
	"webcopier",
	"webcorp",
	"webdatastats",
	"webdoc",
	"webenhancer",
	"webfetch",
	"webfuck",
	"webgazer",
	"webgo is",
	"webimagecollector",
	"webimages",
	"webindex",
	"webkit2png",
	"webleacher",
	"webmastercoffee",
	"webmon ",
	"webpix",
	"webreaper",
	"websauger",
	"webscreenie",
	"webshag",
	"webshot",
	"website quester",
	"websitepulse agent",
	"websitequester",
	"websnapr",
	"websniffer",
	"webster",
	"webstripper",
	"websucker",
	"webthumb/",
	"webthumbnail",
	"webwhacker",
	"webzip",
	"welikelinks",
	"wepa",
	"wesee",
	"wf84",
	"wfuzz/",
	"wget",
	"whatsapp",
	"whatsmyip",
	"whatweb",
	"wheregoes",
	"whibse",
	"whorunscoinhive",
	"whynder magnet",
	"windows-rss-platform",
	"winpodder",
	"wkhtmlto",
	"wmtips",
	"woko",
	"wolfram httpclient",
	"woorankreview",
	"word/",
	"wordpress/",
	"wordupinfosearch",
	"worldping-api",
	"wotbox",
	"wp engine install performance api",
	"wpif",
	"wprecon.com survey",
	"wpscan",
	"wscheck",
	"wtrace",
	"www-collector-e",
	"www-mechanize",
	"www.monitor.us",
	"www::document",
	"www::mechanize",
	"wwwoffle",
	"x09mozilla",
	"x22mozilla",
	"xaxissemanticsclassifier",
	"xenu link sleuth",
	"xing-contenttabreceiver",
	"xpymep",
	"y!j-brw",
	"yaanb",
	"yacy",
	"yahoo link preview",
	"yahoocachesystem",
	"yahooysmcm",
	"yandeg",
	"yandex",
	"yanga",
	"yeti",
	"yo-yo",
	"yoleo consumer",
	"yooglifetchagent",
	"yottaamonitor",
	"your-website-sucks",
	"yourls.org",
	"yoys.net",
	"yp.pl",
	"zabbix",
	"zade",
	"zao",
	"zauba",
	"zemanta aggregator",
	"zend\\http\\client",
	"zend_http_client",
	"zermelo",
	"zeus ",
	"zgrab",
	"znajdzfoto",
	"znhttp",
	"zombie.js",
	"zoom.mac",
	"zyborg",
}
